Surelog vs Yosys formal verification - Python rewrite
antmicro/yosys-systemverilog pull request #1012
Opened 2022-08-22 12:40 UTC by koluckirafal

This PR is a reimplementation of #935 using Python script, allowing for parallelization in CI environment.

2022-08-25 11:21 UTC, rkapuscik requested changes

2022-08-25 11:21 UTC, rkapuscik commented on formal/skiplist.txt
> +core_interface_array_slice.sv
Should we have some kind of prefix here in case the names overlap across suites and we only want to skip one?

2022-08-25 11:21 UTC, rkapuscik commented on formal_verification.py
> +        if sv2v_pass == False:
This will never happen? I assume you wanted to check `ret_yosys_sv2v` instead, but that's not the flow we want to test either.

2022-08-25 11:21 UTC, rkapuscik commented on formal_verification.py
> +        ret_yosys_sv2v = run_yosys(preprocessed_path, work_dir)
We want to run yosys with original test if able and use sv2v only as a fallback.

2022-08-25 11:27 UTC, rkapuscik requested changes

2022-08-25 11:36 UTC, koluckirafal commented on formal_verification.py
> +        if sv2v_pass == False:
Originally `sv2v_pass` was meant to be configurable, so Yosys+SV2V output could be compared with Surelog operating on both original and converted SystemVerilog source. Later I dropped this idea, because I was asked to make sure both Surelog and Yosys are working on the same preprocessed source.

2022-08-25 11:39 UTC, rkapuscik commented on formal_verification.py
> +        if sv2v_pass == False:
That's still what we want to have longer term, but for now let's at least make sure they always operate on the same source, unprocessed if possible.

2022-08-25 11:42 UTC, koluckirafal commented on formal_verification.py
> +        if sv2v_pass == False:
Originally `sv2v_pass` was meant to be configurable, so Yosys+SV2V output could be compared with Surelog operating on both original and converted SystemVerilog source. Later I dropped this idea, because I was asked to make sure both Surelog and Yosys are working on the same preprocessed source.

2022-08-25 11:46 UTC, koluckirafal commented on formal_verification.py
> +            status = "Y GATE"
Dictionary with result descriptions added - for now they are being printed if no test path was given.

2022-08-25 11:46 UTC, koluckirafal commented on formal_verification.py
> +        ret_yosys_sv2v = run_yosys(preprocessed_path, work_dir)
Fixed.

2022-08-25 11:48 UTC, koluckirafal commented on formal/skiplist.txt
> +core_interface_array_slice.sv
The original script was processing tests from all suites in the same run, so I assumed that the original script didn't expect overlapping names either.

2022-08-25 12:10 UTC, rkapuscik approved these changes

2022-08-26 04:58 UTC, alaindargelas approved these changes

2022-08-26 04:58 UTC, alaindargelas commented on formal_verification.py
> +        "read_verilog -sv %s" % test_path,
Please note a better Yosys Tcl command is (copeid from my regression.tcl local script): 

tee -o $output_dir/yosys_ast.txt read_verilog -dump_ast1 -sv $yosys_command

Yosys supports the tee command in its Tcl interface.

You need do do that for both yosys and sv2v+yosys flows so you always have the AST dumped for debug.

That way the ASTs are dumped in a file and can be diffed.

Similar command need to by used for read_systemverilog (Again from my Tcl script):

tee -o $output_dir/surelog_ast.txt read_systemverilog -dump_ast1 -mutestdout $yosys_command

2022-08-26 11:47 UTC, merged