OpenTitan update
antmicro/yosys-systemverilog pull request #1379
Opened 2023-01-02 15:57 UTC by wsipak

2023-01-04 08:33 UTC, rkapuscik requested changes

2023-01-05 15:55 UTC, wsipak commented on .github/workflows/main.yml
> +    - name: Parse OpenTitan components
Alright, the previous flow for OpenTitan remains.

2023-01-05 15:55 UTC, wsipak commented on .github/workflows/main.yml
> +    if: ${{ false }}  # we're transitioning to a newer revision of OT, TODO adjust this job if needed
I've removed the `opentitan_bisect` job.

2023-01-05 15:58 UTC, wsipak commented on uhdm-tests/opentitan/0001-FuseSoC.patch
> ++        except:
I've adjusted it accordingly. We're expecting `SyntaxError` here. In my view this exception class is misused in FuseSoC but the `except` clause now expects only this specific type.

2023-01-05 16:02 UTC, wsipak commented on uhdm-tests/opentitan/0001-OT.patch
> ++        yosys_read_options: ['-noassert', '-defer', '-dump_ast1', '-dump_ast2', '-no_dump_ptr']
I had overlooked this and actually this was an artifact of the previous setup of Edalize to interface with Surelog. In my view we'd need a solution that won't require us to put arguments in every `.core` file, so I've modified it and now the `-defer` option is used by default here:
https://github.com/antmicro/edalize/blob/yosys_systemverilog/edalize/yosys.py#L88-L93
and in the same code fragment `read_systemverilog -link` is added to the list of commands.

2023-01-05 16:03 UTC, wsipak commented on uhdm-tests/opentitan/0001-OT.patch
> ++  VERILATOR_TEST_STATUS_ADDR:
I've removed the ones that mentioned Verilator.

2023-01-05 16:04 UTC, wsipak commented on uhdm-tests/opentitan/Makefile.in
> +	cat ${OPENTITAN}/result.txt | tee ${GITHUB_STEP_SUMMARY}
Alright, now the only interaction with `$GITHUB_STEP_SUMMARY` is done in the workflow file.

2023-01-09 03:06 UTC, wsipak commented
I should've mentioned that the changes in Edalize are here:
https://github.com/antmicro/edalize/tree/yosys_systemverilog
I've rebased the `uhdm_support` branch on the one currently used in OT.
The changes in `uhdm_support` let us interface with Surelog in Yosys. However, I've modified the parts related to Yosys, in order to make it use the SystemVerilog plugin and now it doesn't call `surelog` to produce UHDM but rather reads `.sv` files in Yosys using `read_systemverilog` command.
Previously it would require passing arugments to Surelog in a `.core` file. This would be problematic as we want to be able to process any core belonging to OT without modifying them. Right now choosing `yosys` in FuseSoC by default uses the SV plugin.

2023-01-09 03:07 UTC, wsipak commented on uhdm-tests/opentitan/0001-OT.patch
> ++        yosys_read_options: ['-noassert', '-defer', '-dump_ast1', '-dump_ast2', '-no_dump_ptr']
I've written about the changes in Edalize here:
https://github.com/antmicro/yosys-systemverilog/pull/1379#issuecomment-1375050198

2023-01-09 10:55 UTC, rkapuscik requested changes

2023-01-09 10:55 UTC, rkapuscik commented on .github/workflows/main.yml
> +  opentitan_748b19_parse:
I think we should change the name of original OT target to include its commit, as it will be "frozen", then work on a "rolling" target named just `opentitan`. This will minimize number of changes as we bump our current target.

2023-01-11 16:30 UTC, mglb requested changes
Please use either `'` or `"` in python scripts, do not mix both in one file.
+ one suggestion in code comment.

Everything else looks OK.

2023-01-12 12:09 UTC, wsipak commented
The report generated again is here:
https://github.com/antmicro/yosys-systemverilog/actions/runs/3901920669#summary-10603438321
The python script now consistently uses `'` for strings.

2023-01-12 12:10 UTC, wsipak commented on uhdm-tests/opentitan/iterate_cores.py
> +        f.write('| ' + str(node) + ' | ' + status + ' |\n')
Thank you, I've applied this change.

2023-01-13 10:56 UTC, tgorochowik approved these changes

2023-01-13 10:57 UTC, merged

2023-01-13 11:00 UTC, tgorochowik commented on .gitmodules
> +	url = https://github.com/lowRISC/opentitan
Let's fix this in a follow up PR