OpenTitan: fail when tests unexpectedly fail or pass
antmicro/yosys-systemverilog pull request #1457
Opened 2023-01-30 16:12 UTC by wsipak

Here's a flow to test the changes with unexpected passes:
https://github.com/antmicro/yosys-systemverilog/actions/runs/4053171175

2023-01-31 15:51 UTC, tgorochowik approved these changes

2023-01-31 18:44 UTC, mglb requested changes

2023-01-31 18:44 UTC, mglb commented on .github/workflows/main.yml
> +        fi
Maybe to make it more idiomatic:
```bash
if grep -iq 'Unexpected \(pass\|fail\)' ./UHDM-integration-tests/opentitan_report.txt; then
  exit 1
fi
```
`'Unexpected'` does the job, but with `pass\|fail` it better tells what this is about. A comment would work too.

2023-02-01 12:01 UTC, wsipak commented
Here's another test run that was expected to fail:
https://github.com/antmicro/yosys-systemverilog/actions/runs/4062858198

2023-02-01 13:41 UTC, merged