Yosys update
antmicro/yosys-systemverilog pull request #1460
Opened 2023-01-31 17:20 UTC by mglb

Remaining problems:
- Formal verification fails for:
  - 1 test from sv2v repository
  - 14 tests from yosys repository

(please ignore `CI: *` commits - those are unrelated maintenance/debugging changes that will be extracted to separate PRs)

2023-02-10 15:38 UTC, kamilrakoczy requested changes

2023-02-10 15:38 UTC, kamilrakoczy commented on .github/workflows/large-designs.yml
> +          make -C ./UHDM-integration-tests -j1 TEST=${TEST_CASE} env
Please add comment why we need to set ``-j1``. I suspect it is due to: https://github.com/SymbiFlow/make-env/pull/40

2023-02-10 15:38 UTC, kamilrakoczy commented on .gitmodules
> +	url = https://github.com/antmicro/yosys.git
Revert this change.

2023-02-10 15:38 UTC, kamilrakoczy commented on .gitmodules
> +	path = uhdm-tests/ibex/make-env
I'm not sure about this change, ultimately we would also use it with opentitan, so maybe instead move it to ``third_party``? WDYT?

2023-02-10 15:38 UTC, kamilrakoczy commented on uhdm-tests/ibex/Makefile.in
> +			'$(this_makefile)' )
I think we would like to fail execution if patch fails to apply. In current approach it is easier to miss the message when it is run locally.

2023-02-10 15:58 UTC, mglb commented on .gitmodules
> +	url = https://github.com/antmicro/yosys.git
No, we're using a fork for now (see description).

2023-02-10 16:30 UTC, mglb commented on uhdm-tests/ibex/Makefile.in
> +			'$(this_makefile)' )
If it still works with a failed patch (and patching will most likely fail only when the fix end up on upstream, in which case the build should work), does it really matter? It would cause failures in CI and local builds just because of a minor warning.

I can add a more noticeable message printed at the end of the build/log (including after a failure), to let user know what could have caused a build error. Would this suffice?

2023-02-10 17:59 UTC, kamilrakoczy commented on uhdm-tests/ibex/Makefile.in
> +			'$(this_makefile)' )
> If it still works with a failed patch (and patching will most likely fail only when the fix end up on upstream, in which case the build should work), does it really matter? It would cause failures in CI and local builds just because of a minor warning.

I think it matters, as then we know that this patch is no longer necessary. This step is also in the middle and can be easily overseen. 

> I can add a more noticeable message printed at the end of the build/log (including after a failure), to let user know what could have caused a build error. Would this suffice?

Yes, this is fine for me also.

2023-02-10 18:01 UTC, kamilrakoczy commented on .gitmodules
> +	url = https://github.com/antmicro/yosys.git
Oh, ok, so maybe we can still track upstream, but apply this fix as a patch?

2023-02-13 08:58 UTC, mandrys approved these changes

2023-02-13 09:19 UTC, wsipak approved these changes

2023-02-13 10:24 UTC, mglb commented on .gitmodules
> +	url = https://github.com/antmicro/yosys.git
This would be a good idea generally. However, I'll make the PR in Yosys today, and the fix itself is really uncontroversial and small, so it should be merged reasonably fast. After that merge, which I hope will happen this week, we'll switch to upstream. Not many bumps would happen in between, I guess :)

2023-02-13 14:27 UTC, mglb commented on uhdm-tests/ibex/Makefile.in
> +			'$(this_makefile)' )
The warning is now printed *after* `env` target completes.
The warning is not printed when the env creation failed because it can't fail due to the patch. Such warning would just shadow an actual error.

The CI warning in always emitted when patching failed.

**The error with TTY stdout:**

![Screenshot_20230213_131625](https://user-images.githubusercontent.com/4888536/218483023-ae5565e6-f00e-4df0-8063-1af1718c16f7.png)

**Non-TTY stdout:**

![Screenshot_20230213_132053](https://user-images.githubusercontent.com/4888536/218483033-728bc5af-4151-4ef3-bb5e-7261ecd7e3bd.png)

2023-02-13 14:28 UTC, mglb commented
I've also bumped make-env.

2023-02-13 14:36 UTC, mglb commented
Ignoring tuttest failure. This has been fixed on master and would require rebase and yet another CI run.

2023-02-13 14:36 UTC, merged