Fix formal verification
antmicro/yosys-systemverilog pull request #1485
Opened 2023-02-07 17:09 UTC by mglb

The formal verification results are not repeatable. The same commit tested twice gives different counts of performed (failed) tests.
This is caused by a bug that crashes formal_verification.py and the fact that a single invocation of the script is intended to perform multiple tests in a loop. The tests given to a script are always the same (it takes a directory name and performs all tests in that directory), but their order is pseudo-random. When one test crashes the script, all remaining tests are not performed.

This PR fixes this problem by fixing known crashes and using one script invocation to perform just one test.
Additional changes:
- Changed naming convention to one that is more readable and stable.
- Added a pass that checks whether every test from the passlist.txt has been performed.
- Minor improvements in logging

2023-02-08 08:58 UTC, mglb commented
Note to reviewers: I think this can be looked at commit-by-commit, all except [9a528f4](https://github.com/antmicro/yosys-systemverilog/pull/1485/commits/9a528f4f3cdc9ea114c849a36be3d92f207fa085) change one thing at a time.

2023-02-08 09:22 UTC, kamilrakoczy requested changes

2023-02-08 09:22 UTC, kamilrakoczy commented on formal_verification.py
> +    process = subprocess.run([*make_timeout_cmd(5*60), "sv2v", test_sources, "-w=%s" % sv2v_out])
Timeout is already in ``s``. I think you wanted to set timeout to ``5s`` not ``300s``). The same applies to other usages of ``make_timeout_cmd``.

2023-02-08 09:22 UTC, kamilrakoczy commented on formal/formal_results.py
> +                    f"Missing key `{result}` in `{result_data!r}`.\n")
Could you please add comment when this can happen and why we don't fail on such cases?

2023-02-08 09:22 UTC, kamilrakoczy commented on formal/formal_results.py
> +                continue
Could you please add comment when this can happen and why we don't fail on such cases?

2023-02-08 10:02 UTC, mglb commented on formal_verification.py
> +    process = subprocess.run([*make_timeout_cmd(5*60), "sv2v", test_sources, "-w=%s" % sv2v_out])
I did actually want 5min (300s). This is just to prevent a test from hanging for 6 hours, until job timeout, and preventing remaining tests from running.
It makes sense to lower this value through, but the question is how much? Random tests I did look at right now take 2..3s total, and they don't access the network, so it shouldn't become much longer.
I'll check logs to see what is the longest execution time.

2023-02-08 10:08 UTC, mglb commented on formal/formal_results.py
> +                    f"Missing key `{result}` in `{result_data!r}`.\n")
I had results with `{status: "SKIPPED"}`, where e.g. "yosys" key has been absent, but I guess I've removed code causing this. I'll change the code to report a failure instead.

2023-02-08 10:44 UTC, mandrys approved these changes

2023-02-08 10:51 UTC, wsipak approved these changes

2023-02-09 13:00 UTC, mglb commented on formal/formal_results.py
> +                continue
Removed this one and left comment instead - any key-related issues would be caught in the previous loop.

2023-02-09 13:07 UTC, mglb commented on formal_verification.py
> +    process = subprocess.run([*make_timeout_cmd(5*60), "sv2v", test_sources, "-w=%s" % sv2v_out])
I've added `print`s with execution duration of each process and updated timeout limits to more reasonable durations.

2023-02-09 13:16 UTC, mglb commented on formal/formal_results.py
> +                    f"Missing key `{result}` in `{result_data!r}`.\n")
Added a comment and slightly changed the message.
Test run with intentionally introduced `results.json` errors can be seen [here][errrun].
A message shows which file caused the problem, and clicking it leads to log with the exception printed.
Note that the `$` visible in messags in the linked run has been removed in code introduced to this PR.

[errrun]: https://github.com/antmicro/yosys-systemverilog/actions/runs/4126449557

2023-02-09 13:19 UTC, kamilrakoczy approved these changes

2023-02-09 18:28 UTC, merged