CI: Fold and merge tables in parsing tests results summary.
antmicro/yosys-systemverilog pull request #1539
Opened 2023-02-27 12:24 UTC by mglb

When everything passed, the list of tests is initially folded.

[Live demo](https://github.com/antmicro/yosys-systemverilog/actions/runs/4258279850)

![Screen Shot 2023-02-27 at 13 04 22](https://user-images.githubusercontent.com/4888536/221559889-7a90e15c-3a5d-4967-a195-38d0b1b3935e.png)

---

When there are failures, their list is initially visible. The separate list of passed tests is initially folded. Note: failures on the screenshot are made up and were artificially injected into test outputs just to show and test how it would look.

[Live demo](https://github.com/antmicro/yosys-systemverilog/actions/runs/4258278521)

![Screen Shot 2023-02-27 at 13 04 36](https://user-images.githubusercontent.com/4888536/221560909-b4453291-a6b9-428c-b684-35a375f21111.png)

---

Up until now there were two tables. Both with the same tests, but with results for different tool.
Now there's just one table, with results for both tools in separate columns.

![Screen Shot 2023-02-27 at 13 05 29](https://user-images.githubusercontent.com/4888536/221562159-433040a8-cbec-4023-9d8c-a3f0e306da60.png)

2023-02-27 15:01 UTC, wsipak requested changes

2023-02-27 15:38 UTC, kamilrakoczy approved these changes

2023-02-27 17:53 UTC, mglb commented on .github/scripts/generate_summary.sh
> +declare -a results_11=()
They represent success or failure, yes. However, they also represent an actual value read from status files.
As you can see in the `case` below, it checks `${uhdm_results[$test_name]:-0}${systemverilog_results[$test_name]:-0}`, which expands to one of: `00`, `01`, `10`, `11`. So e.g. `results_00` contains literally "test names with results, respectivelly, `0` and `0`.
Another advantage of those names is that it is harder to mess up case value and array name when you have code like `11) results_11+=...`. It would be even better with `0` instead of `[^1]`.
You can also think about digits in those names just as "status in the first column" and "status in the second column", without really linking them to actual names. However, this would work better if the column names were stored in an array instead of being hardcoded.

TL;DR: Would comment above the names be sufficient? If not, I'll change the names, as the suggestion is generally OK.

Note:
The case actually checks for anything except `1` instead of zero, just in case something weird ends up in the file instead of `0`. I think such thing happening has a very low probability. I'm willing to change `[^1]` to `0` if you would like so.

2023-02-28 11:40 UTC, wsipak commented on .github/scripts/generate_summary.sh
> +declare -a results_11=()
Alright, I can see these names actually make sense. I think we would benefit from having a comment clarifying what these names mean, and that should be sufficient. Thanks!

2023-02-28 15:42 UTC, merged