Sort formal verification passlists
antmicro/yosys-systemverilog pull request #1718
Opened 2023-05-16 14:09 UTC by kamilrakoczy

Requires: https://github.com/antmicro/yosys-systemverilog/pull/1716
Sorted using:
```
LANG=C sort -f -u -o formal/passlist.txt formal/passlist.txt
LANG=C sort -f -u -o uhdm-tests/opentitan/opentitan_parsing_test/ot-cores-passlist.txt uhdm-tests/opentitan/opentitan_parsing_test/ot-cores-passlist.txt
```
This PR also adds check to CI to make sure this lists are sorted.

2023-05-17 12:01 UTC, wsipak commented on .github/workflows/formal-verification.yml
> +    container: bitnami/git:2.40.1-debian-11-r4
What is the reason of this change?

2023-05-17 12:06 UTC, kamilrakoczy commented on .github/workflows/formal-verification.yml
> +    container: bitnami/git:2.40.1-debian-11-r4
``ubuntu`` container by default doesn't have ``git``. I could install it using ``apt``, but as we only need ``git``, it is probably better to use container with ``git`` already installed (we are also already using this container in ``emit-workflow-info`` job: https://github.com/antmicro/yosys-systemverilog/blob/master/.github/workflows/main.yml#L37.

2023-05-17 12:10 UTC, wsipak commented on .github/workflows/formal-verification.yml
> +    container: bitnami/git:2.40.1-debian-11-r4
Alright, thanks!

2023-05-19 09:35 UTC, mglb commented on .github/workflows/formal-verification.yml
> +    container: bitnami/git:2.40.1-debian-11-r4
This is also a container I've used for another job, so it is already tested on production (for short time, but still).
Also, this container is maintained by Bitnami, which is VMware. Trustworthy enough for CI purposes.

2023-05-19 09:40 UTC, mandrys approved these changes

2023-05-19 10:11 UTC, mglb requested changes

2023-05-19 10:11 UTC, mglb commented on .github/workflows/formal-verification.yml
> +                                                            false; }
Maybe something like this?
```
files_to_sort_check=(
  formal/passlist.txt
  uhdm-tests/opentitan/opentitan_parsing_test/ot-cores-passlist.txt
)
for f in "${files_to_sort_check[@]}"; do
  if ! git diff --exit-code $f; then
    echo
    echo "Sort locally using:"
    echo "LC_ALL=C.UTF-8 sort -f -u -o $f $f"
    echo
  fi
done
```
Separate check for each list, simpler condition, and a more usual `if` syntax.

2023-05-19 10:11 UTC, mglb commented on .github/workflows/formal-verification.yml
> +          LANG=C sort -f -u -o uhdm-tests/opentitan/opentitan_parsing_test/ot-cores-passlist.txt uhdm-tests/opentitan/opentitan_parsing_test/ot-cores-passlist.txt
- Use `LC_ALL=C` instead of `LANG` - the latter is a default used only when `LC_COLLATE` (which is used for controlling sorting behavior) is not set. The former overrides `LC_COLLATE` and other `LC_*` values.
- To avoid repetition put it either in `env:` or export it at the beginning of the script.

2023-05-31 09:18 UTC, kamilrakoczy commented on .github/workflows/formal-verification.yml
> +                                                            false; }
I actually moved whole sorting to bash script and changed message to user to use this script. I think this is better. WDYT?

2023-05-31 15:30 UTC, mglb commented on .github/workflows/formal-verification.yml
> +                                                            false; }
Good idea.

2023-06-02 12:42 UTC, merged