Bsg formal duts tests generator
antmicro/yosys-systemverilog pull request #1732
Opened 2023-05-19 08:17 UTC by mandrys

2023-05-22 12:15 UTC, tgorochowik commented on .gitmodules
> +	url = https://github.com/bsg-idea/bsg_micro_designs.git
Can this be excluded from dependabot updates? I think we depend on a particular version here

2023-05-22 12:44 UTC, mandrys commented on .gitmodules
> +	url = https://github.com/bsg-idea/bsg_micro_designs.git
Right, I'll do it

2023-06-06 13:39 UTC, mandrys commented on .gitmodules
> +	url = https://github.com/bsg-idea/bsg_micro_designs.git
Done in https://github.com/antmicro/yosys-systemverilog/pull/1732/commits/613c33fb48910e1d5981d494660ee3e8acd7c64d.

2023-06-07 09:29 UTC, kamilrakoczy approved these changes

2023-06-07 10:12 UTC, wsipak requested changes

2023-06-07 10:12 UTC, wsipak commented on generate_bsg_tests.py
> +        if len(passlist):
According to [the docs](https://docs.python.org/3/library/stdtypes.html#truth-value-testing) empty lists should be falsy, so
    `if len(passlist):`
would be equivalent to
    `if passlist:`

[PEP8](https://peps.python.org/pep-0008/#programming-recommendations) suggests this way of checking if a collection is empty.
There are several usages of `if len(foo):` here. Could we have this changed into `if foo:`?

2023-06-07 10:39 UTC, mandrys commented on generate_bsg_tests.py
> +        if len(passlist):
Thanks for spotting this! Applied the change.

2023-06-07 11:58 UTC, wsipak commented on generate_bsg_tests.py
> +        if len(passlist):
Thank you!

2023-06-12 14:11 UTC, mglb requested changes
Logic is OK.

The most important comments are:
- Suggestion to move bsg_micro_designs repo to uhdm-tests
- Summary text formatting
- `matrix.name`
- Using python instead of sed

2023-06-12 14:11 UTC, mglb commented on generate_bsg_tests.py
> +    sp = subprocess.run(["sed -i -e '/\(\* .* \*\)/d' -e '/^\s*$/d' %s" % filename], shell=True)
Can you do this in Python?
```python
with open(filename, "r+") as f:
    s = f.read()
    s = re.sub(r'\(\*.+?\*\)|/\*.*?\*/|\s*$', '', s)
    ...
    f.seek(0)
    f.write(s)
    f.truncate()
```
But please verify this code, especially the regexp
Note: `.+?` and `.*?` are non-greedy equivalents of `.+` and `.*`.

2023-06-12 14:11 UTC, mglb commented on generate_bsg_tests.py
> +            gen_tests(test_name, os.path.relpath(sub_suite_dir), ref_test_dir, output_dir)
Let's stick to `Path`, especially since we already have variable of this type.
```suggestion
            test_name = json_file.parent.name
            gen_tests(test_name, sub_suite_dir, ref_test_dir, output_dir)
```
I've removed the relpath above to support running from different directories than the one expected, but `sub_suite_dir.relative_to(Path.cwd())` should work if you really need a relative path.

2023-06-14 14:06 UTC, mglb requested changes
Just one thing, the rest looks nice.

2023-06-14 14:06 UTC, mglb commented on .github/workflows/bsg-test-diff.yml
> +            uhdm-tests/bsg_micro_designs/build
I think it would be better to upload two separate packages - one for new dut.v files (for everyone interested), and one for logs (for debugging).
For example:
```
name: bsg-outputs
path: uhdm-tests/bsg_micro_designs/build/*/dut.v
```
```
name: bsg-logs
path: |
  uhdm-tests/bsg_micro_designs/build/*
  !uhdm-tests/bsg_micro_designs/build/*/dut.v
```

2023-06-14 14:18 UTC, mandrys commented on .github/workflows/bsg-test-diff.yml
> +            uhdm-tests/bsg_micro_designs/build
Should I put the diffs with logs then?

2023-06-14 14:37 UTC, mglb commented on .github/workflows/bsg-test-diff.yml
> +            uhdm-tests/bsg_micro_designs/build
Good question. Let's put diffs with dut.v, so something like:

```
name: bsg-outputs
path: |
  uhdm-tests/bsg_micro_designs/build/*/dut.v
  uhdm-tests/bsg_micro_designs/build/*/dut.v.diff
```

```
name: bsg-logs
path: |
  uhdm-tests/bsg_micro_designs/build/*
  !uhdm-tests/bsg_micro_designs/build/*/dut.v
  !uhdm-tests/bsg_micro_designs/build/*/dut.v.diff
```

2023-06-14 14:51 UTC, mandrys commented on .github/workflows/bsg-test-diff.yml
> +            uhdm-tests/bsg_micro_designs/build
Or wait a second...

2023-06-14 14:56 UTC, mandrys commented on .github/workflows/bsg-test-diff.yml
> +            uhdm-tests/bsg_micro_designs/build
OK, now it's done.

2023-06-15 08:46 UTC, merged

2023-06-15 10:02 UTC, mglb commented
@BrendenPage you can find new dut.v files generated from BSG Micro Designs in `bsg-outputs` artifact of this PR's CI run. Direct link: https://github.com/antmicro/yosys-systemverilog/suites/13602743129/artifacts/750131825