CI: add job storing AST results in different repository
antmicro/yosys-systemverilog pull request #1759
Opened 2023-06-02 11:17 UTC by kamilrakoczy

This PR adds new CI jobs that pushes AST to ``yosys-systemverilog-logs`` repository. This allows to easily view diff of AST between introduced changes.

URL with diff is posted as both github actions summary as well as PR comment (when event is pull_request).

Currently it only works when submodules are override using branches instead of whole url.

2023-06-05 12:41 UTC, mglb commented on .github/workflows/parsing-tests.yml
> +          create-target-branch-if-needed: true
Can you just manually do it using git here?
It's better than running action from random person.

2023-06-05 12:41 UTC, mglb commented on .github/workflows/parsing-tests.yml
> +
As above, can you do that using `gh` or `curl`?

2023-06-05 15:38 UTC, wsipak approved these changes

2023-06-05 18:08 UTC, mglb commented on .github/workflows/parsing-tests.yml
> +
Possibly even better option: https://github.com/actions/github-script
There's even an example for posting a comment: https://github.com/actions/github-script#comment-on-an-issue

2023-06-07 10:01 UTC, kamilrakoczy commented on .github/workflows/parsing-tests.yml
> +                github.rest.issues.deleteComment({
The idea was that ``yosys-systemverilog-logs`` master sha could change between job re-run, so in such case, we want to delete previous comment, and post new one with updated SHA, but I've just noticed, that I'm posting everything in single line, so it wouldn't work as I intended.

I pushed fix for this. Now link to the diff should be on separate line from ``Logs difference between main branch:``.

2023-06-07 10:25 UTC, mandrys commented on .github/workflows/parsing-tests.yml
> +                github.rest.issues.deleteComment({
Ok, I get it :)

2023-06-07 10:26 UTC, mandrys approved these changes

2023-06-07 16:57 UTC, mglb requested changes
Code-only review so far.
I'll test it in practice, generally looks nice.

2023-06-07 16:57 UTC, mglb commented on .github/workflows/parsing-tests.yml
> +          if [[ ! -z "$PLUGINS_BRANCH_SPEC" ]]; then
Just FYI: `! -z` == `-n`.

2023-06-07 16:57 UTC, mglb commented on .github/workflows/parsing-tests.yml
> +
```suggestion
          .github/scripts/push_to_another_repository.sh "$GITHUB_REPOSITORY_OWNER" "$PUSH_BRANCH" "$GITHUB_RUN_ID" logs

```

Safer.

2023-06-07 16:57 UTC, mglb commented on .github/scripts/push_to_another_repository.sh
> +GIT_CMD_REPOSITORY="git@github.com:$REPOSITORY_OWNER/yosys-systemverilog-logs.git"
If we hardcode repository name, why not the owner?
Just put at the top of the file:
```
declare -r LOGS_REPO_PUSH_URL='git@github.com:antmicro/yosys-systemverilog-logs.git'
```
and use that, or take it as an argument.

2023-06-07 16:57 UTC, mglb commented on .github/scripts/run_group_test.sh
> +    $ROOT_DIR/UHDM-integration-tests/.github/ci.sh | sed -e 's#'${ROOT_DIR_ABSOLUTE}'##g' | sed -e 's/\(End of script\).*//' | sed -e 's/\(Time spent\).*//' | tee $LOG_DIR/$TEST_CASE/ast.log
```suggestion
    ROOT_DIR_ABSOLUTE=$(realpath $ROOT_DIR)/
    $ROOT_DIR/UHDM-integration-tests/.github/ci.sh \
        | sed -e "s#${ROOT_DIR_ABSOLUTE}##g" \
            -e 's/\(End of script\).*//' \
            -e 's/\(Time spent\).*//' \
                | tee $LOG_DIR/$TEST_CASE/ast.log
```

2023-06-07 16:57 UTC, mglb commented on .github/workflows/parsing-tests.yml
> +            PUSH_BRANCH="$PUSH_BRANCH+plugins+$PLUGINS_BRANCH_SPEC"
```suggestion
            PUSH_BRANCH="${PUSH_BRANCH}+{plugins}+${PLUGINS_BRANCH_SPEC}"
```
readability, especially due to `${VARNAME+}` being a thing.

2023-06-07 16:57 UTC, mglb commented on .github/scripts/push_to_another_repository.sh
> +COMMIT_MESSAGE="${COMMIT_MESSAGE/\$GITHUB_REF/$GITHUB_REF}"
Too much indirection.

```suggestion
printf -v COMMIT_MESSAGE 'Update logs from https://github.com/%s/actions/runs/%s\n' \
    "$GITHUB_REPOSITORY" "$GITHUB_RUN_ID"
```
Is this equivalent?

2023-06-07 16:57 UTC, mglb commented on .github/workflows/parsing-tests.yml
> +
Maybe rename the script to "push_to_logs_repository"?

2023-06-07 16:57 UTC, mglb commented on .github/workflows/parsing-tests.yml
> +            const newComment = '${{ env.COMMENT_MSG }}';
Code injection possible, COMMENT_MSG contains raw branch name.

2023-06-09 05:59 UTC, kamilrakoczy commented on .github/workflows/parsing-tests.yml
> +            PUSH_BRANCH="$PUSH_BRANCH+plugins+$PLUGINS_BRANCH_SPEC"
Should ``plugins`` also have ``{}`` around it? Or you wanted to change branch name too?

2023-06-09 06:15 UTC, kamilrakoczy commented on .github/scripts/push_to_another_repository.sh
> +GIT_CMD_REPOSITORY="git@github.com:$REPOSITORY_OWNER/yosys-systemverilog-logs.git"
It was for forks, if you would like to test some new feature that requires some extra configuration (e.g. extra secret) while still want to push logs, it should work out-of-the box. Repository name is hardcode, as I think even forked repositories wouldn't like to change it.

You need to setup proper SSH_DEPLOY_KEY in repository secrets to allow pushing to specific logs repository, so I think taking it as an argument doesn't make sense.

2023-06-09 06:33 UTC, kamilrakoczy commented on .github/workflows/parsing-tests.yml
> +          if [[ ! -z "$PLUGINS_BRANCH_SPEC" ]]; then
Thanks, I didn't know that, but I left ``! -z``. If you prefer ``-n`` I can change it, but I think ``! -z`` is more know.

2023-06-09 06:38 UTC, kamilrakoczy commented on .github/workflows/parsing-tests.yml
> +            const newComment = '${{ env.COMMENT_MSG }}';
You are right, I've changed it, but tbh, I'm not sure if this should be considered a real threat.

If someone would like to inject code, he could just change workflow file itself, or maybe I'm missing something and such code injection have bigger permissions than just changing code itself?

2023-06-09 11:07 UTC, mglb commented on .github/workflows/parsing-tests.yml
> +            const newComment = '${{ env.COMMENT_MSG }}';
AFAIR PRs either run agains CI from master, or require manual approval when they change a CI workflow, don't remember which one, if any.

But there are also other reason to avoid it everywhere, at least when there is no explicit comment about it:
- copy-paste, or changes around code, happen
- bad habits are bad

As for the solution for this and generally access to env in github-script, you can do:
```
      - uses: actions/github-script@v6
        env:
          - COMMIT_MSG: ${{ env.COMMIT_MSG }}
          - SOMETHING_OTHER: a value
        with:
          script: |
            const {COMMIT_MSG, SOMETHING_OTHER} = process.env;
            const or_just_directly = process.env.COMMIT_MSG;
```

It is possible that it works even without explicit reassignment in `env` when the variable has been set in a previous step, but I'm not sure about this.

2023-06-09 11:08 UTC, mglb commented on .github/workflows/parsing-tests.yml
> +            PUSH_BRANCH="$PUSH_BRANCH+plugins+$PLUGINS_BRANCH_SPEC"
Oh, sorry! No, it should be `${PUSH_BRANCH}+plugins+${PLUGINS_BRANCH_SPEC}`.

2023-06-09 11:13 UTC, mglb commented on .github/workflows/parsing-tests.yml
> +          if [[ ! -z "$PLUGINS_BRANCH_SPEC" ]]; then
`! -z` is OK too.

2023-06-09 11:15 UTC, mglb commented on .github/scripts/push_to_another_repository.sh
> +GIT_CMD_REPOSITORY="git@github.com:$REPOSITORY_OWNER/yosys-systemverilog-logs.git"
Makes sense.

2023-06-09 12:12 UTC, mglb approved these changes

2023-06-09 16:30 UTC, merged